version: "2" 

plugins:
  fixme:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true


exclude_patterns:
  - "tools/"
  - "scripts/"
  - "test/"
  - "**/modernizr.js"
