engines:
  fixme:
    enabled: false
  duplication:
    enabled: false

plugins: 
  eslint:
    enabled: true
  csslint:
    enabled: true

exclude_patterns:
  - "tools/"
  - "scripts/"
  - "test/"
  - "**/modernizr.js"
